# (Args)
# ARG: BASE_IMAGE
# ARG: USER_UID


ARG BASE_IMAGE=python:3.8-slim-buster


FROM ${BASE_IMAGE}

# system update & package install
RUN apt-get clean && \
    apt-get -y update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libpcre3 libpcre3-dev \
    zlib1g zlib1g-dev \
    openssl libssl-dev
# todo: 要不要の選別など

# user        
# ref:
# https://zukucode.com/2019/06/docker-user.html
# https://qiita.com/Riliumph/items/3b09e0804d7a04dff85b
# 一般ユーザーアカウントを追加
ENV USER_NAME=app
ARG USER_UID=1000
RUN useradd -m -u ${USER_UID} ${USER_NAME}
# 一般ユーザーにsudo権限を付与
#RUN gpasswd -a ${UID} sudo


# https://medium.com/@rlagowski/create-flask-app-with-uwsgi-nginx-certbot-for-ssl-and-all-this-with-docker-a9f23516618d
#COPY --chown=app:app ./${PIP_REQUIREMENTS} /app/requirments.txt
#COPY --chown=app:app ./app /app
COPY ./requirements.txt /app/requirements.txt
COPY ./app /app
RUN chown -R ${USER_NAME}:${USER_NAME} /app # --chown= では環境変数の代入が効かない

USER ${USER_UID}
WORKDIR /app

# pip
RUN python3 -m pip install --user --upgrade pip && \
    python3 -m pip install -r requirements.txt --user
ENV PATH $PATH:/home/app/.local/bin

CMD ["uwsgi", "--ini", "uwsgi.ini"]

